### ISSUE TITLE
high cpu when sddm-greeter is idle

### ISSUE THREAD

**Issue by jpsinthemix** [sddm/sddm#323]
I'm playing around with kf5 and would like to use sddm. I build all packages (similar to lfs) and while sddm appears to be functioning, there are several issues which are show-stoppers in my judgement. I'll focus on one here: once sddm-greeter has started and is simply idling, waiting for user login (the password entry field has focus), sddm-greeter shows an alarmingly high cpu usage. In particular, by theme, we have:
  breeze .. 5-10 % cpu
  maui ..... 60-80 % cpu
  circles ... 20-27 % cpu

Observations:
- once logged in, cpu usage drops to 0-0.7 % cpu
- in the maui theme, if I do not set focus: true in the listview element, then sdd-greeter will start up
  without the password field having focus, and we get 0 % cpu; but as soon as I click on the  password field, cpu usage goes to 60-80 %
- in the maui theme, if I remove the clock from Main.qml, we get 23-28 % cpu

Systems:
All are i686-pc-linux-gnu, with qt-opensource5.5.3.2, gcc-4.9.2, glibc-2.20, linux-3.17.4, and systemd-217
All exhibit the same behavior, same cpu usage
One system uses llvmpipe, one uses i915/opengl 2.1, and another a radeon x1400/opengl 2.1

It looks kinda like something is triggering qt/qtquick to do screen updates frequently and unnecessarily. Has anyone else seen this kind of behavior ?

**Comment by jleclanche** [comment]
I finally managed to reproduce this on one of my lower-grade machines.

**Comment by jpsinthemix** [comment]
I looked into this a bit more a while ago, and put it on hold for the time being. This is not an sddm bug, but simply due to the qtquick2 scenegraph implementation, particularly the use of shaders too complex for older GPUs to handle. GPUs with limited opengl 2.0 functionality (specifically, limited shader capability) will either not work at all or exhibit extremely poor performance with QtQuick2. For example, Thinkpad R51's using the i915 driver (with marginal opengl 2.0 support) show very poor performance: only 1-3 texture calls are supported in a shader; if a shader has more texture calls, swrast calls are triggered-- leading to the poor performance.

As a quick (Qt-5.4.0) workaround, one can set the Qt (subpixel anti-aliasing text rendering) environment variable QSG_DISTANCEFIELD_ANTIALIASING=subpixel-lowq, eg,
QSG_DISTANCEFIELD_ANTIALIASING DEFAULT=subpixel-lowq in /etc/security/pam_env.conf.

The default Qt5Quick anti-aliasing shader employs the shader pair hiqsubpixeldistancefieldtext.{vert,frag} which has more than 3 texture calls, whereas 'subpixel-lowq' uses loqsubpixeldistancefieldtext.{vert,frag} which has fewer calls. This is likely only a temporary 'fix' since presumably QtQuick, KF5, and others will increasingly make use of shaders too complex for most older GPUs. Currently (as of Qt-5.4.0), Qt5Gui and Qt5Declarative (QtQuick1) will still work fine on GPUs with opengl <= 2.0, but this is of little value to end-users since kframeworks and others would have to implement this support along with QtQuick2 support, which they apparently have no interest in doing.

**Comment by plfiorini** [comment]
Mmmm unfortunately I don't think there's much we can do here.

**Comment by plfiorini** [comment]
@jleclanche How much lower grade?

**Comment by damianb** [comment]
@plfiorini I have a cr48 and was encountering this, if that helps. It's a little Intel Atom in there, so intel gfx.

**Comment by jleclanche** [comment]
@plfiorini first gen asus eee :p

**Comment by jleclanche** [comment]
Intel gfx as well on it.

**Comment by tsjk** [comment]
I observed this on a ASUS EeePC 901. Intel GFX on that too. Since then I've installed KitKat on that machine, so I for one do not care anymore.

**Comment by hogend** [comment]
On a core i5 4570, sddm-greeter takes between 3 and 6% CPU (breeze theme) when idling. This is IMNSHO insane. Please, fix this to stop global warming.

**Comment by damianb** [comment]
@hogend Can you state what GPU, for the record?

**Comment by hogend** [comment]
The internal GPU, which is an Intel HD Graphics 4600.

Regards,

 

Rene

**Comment by jpsinthemix** [comment]
The problem is not with sddm, but with QtQuick2 (qtdeclarative); currently, has to do with how qtquick2 renders text; you can try:

echo 'QSG_DISTANCEFIELD_ANTIALIASING DEFAULT=subpixel-lowq' \
   >> /etc/security/pam_env.conf

to force the use of a simply shader.

**Comment by xiangzhai** [comment]
So is it possible to develop traditional QWidget sddm greeter runtime swtich when target PC is very oooooold with limit RESOURCE?

**Comment by plfiorini** [comment]
I don't think QWidget is an option here, it's pointless for a login manager that wants to use recent stuff like QtQuick 2.   Support for OpenGL 1.3 hardware might be achieved setting QT_XCB_FORCE_SOFTWARE_OPENGL=1 (see #575) for example.

Has anyone with the problem tested what happens with a simple theme and Text native rendering type (http://doc.qt.io/qt-5/qml-qtquick-text.html#renderType-prop) to see if that does something?

**Comment by realsobek** [comment]
I am using a virtualized Fedora 24 x86_64 with one CPU in VirtualBox and experience the problem on the login screen. The problem is present, if the cursor is blinking in a text input box.

'/etc/sddm.conf' uses by default the theme 01-breeze-fedora
I installed other themes from the Fedora repository and they all have the same issue.
As far as I can see Fedora llvmpipe. I am not sure, if this invalidates my test results.

In the file `/etc/sddm.conf` starting at line 25 I set the theme to:
```
[Theme]
Current=02-fedora
```

I edited the file: `/usr/share/sddm/themes/02-fedora/Main.qml` starting at line 186 (renderType line was added by me)
```
                    PasswordBox {
                        id: password
                        renderType: Text.NativeRendering
```

And restarted sddm: `su -c 'systemctl restart sddm'`

CPU usage drops from 10% to 0% according to `top`, but screen becomes completely white and unusable. Mouse cursor is not displayed. Removing the 'renderType' line and restarting SDDM make the screen usable again.

Shall I test something else?

**Comment by plfiorini** [comment]
Qt 5.8 will have the ability to pick a different QtQuick backend, including the new 2d backend that doesn't use OpenGL.

http://doc-snapshots.qt.io/qt5-dev/qtquick-visualcanvas-adaptations-software.html

In theory we can make a theme that doesn't use shaders (as far as I remember the themes that we provide do not depend on shaders) and enable the 2d backend making the greeter perform better on such hardware.

We can add a setting with the QtQuick backend that is used only when SDDM is built against Qt 5.8.

**Comment by xiangzhai** [comment]
> Qt 5.8 will have the ability to pick a different QtQuick backend, including the new 2d backend that doesn't use OpenGL.

cool!

**Comment by sven76** [comment]
Is there any progress regarding this problem? 

I'm running sddm on a Clevo W230SS notebook with an Intel HD 4600 card (8086:0416) and I'm still suffering this problem. The breeze theme produces an average cpu last of 30% on an Core-i7 (4712 mq). This runs low the battery in a short time and turns on the noisy fan.

In the meantime we are at QT-5.9. Thereby the choice of the different QtQuick backend should be available. If the problem couldn't be fixed in general, an option to disable the opengl backend in sddm.conf would help.

**Comment by jpsinthemix** [comment]
A  Clevo W230SS notebook w/Intel HD 4600 should should have no problems with qtquick2; you most likely have a bug in the intel hd 4600 driver. Try installing the latest git/development driver from intel.

**Comment by bbkr** [comment]
I installed SDDM on Dell Mini 10v (Intel GMA945 + Atom 270) on bare Arch 32bit distro. Text entering was very laggy, after typing password character dot in text field appeared after 5-10 seconds.

Setting QSG_DISTANCEFIELD_ANTIALIASING reduced the lag to 0.1s. Not perfect but usable.

Thanks for hint!

BTW: Using theme https://store.kde.org/p/1186478/ further reduced input lag.

**Comment by jowagner** [comment]
Since there seems to be no volunteer to implement a more efficient way to let the cursor blink, how about implementing that the cursor stops blinking if there is no mouse or keyboard activity in the last 10 minutes? Optionally show a message "To save energy, the blinking of the cursor has been stopped. The re-activate the login screen, please press Esc or move the mouse.".

**Comment by chriswells0** [comment]
Just an FYI in case it helps someone else who comes across this issue:

I was having this problem on FreeBSD 12, which does not have `/etc/security/pam_env.conf`, so I tried setting the environment variable in `/etc/profile`.  That did set the variable, but it did not resolve the issue.

However, in KDE's System Settings, changing **Display and Monitor** -> **Compositor** -> **Rendering backend** to **OpenGL 2.0** (instead of 3.1) did resolve the issue for me.

**Comment by hcoin** [comment]
The problem still exists in Ubuntu disco.  This problem makes sddm-greeter based distros unsuitable as typical qxl virtual machine guests as well as baremetal hosts on servers that are almost never 'about' graphics cards.   The host has sddm-greeter at 10% cpu or so, plus each guest sucking 10% for nothing.  This reality is entirely contrary to the 'lightweight' advertising these distros feature (some of them).  
Solution:
apt install tasksel
apt update
tasksel install ubuntu-mate-desktop
<Choose lightdm, not sddm when asked>
reboot.

**Comment by ShaheedHaque** [comment]
Using Ubuntu Disco, I found that `QSG_DISTANCEFIELD_ANTIALIASING DEFAULT=subpixel-lowq` had no effect, however, as per #575, this worked just fine:
```
echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf
```

**Comment by lbiiun8** [comment]
1. in KDE's System Settings, changing Display and Monitor -> Compositor -> Rendering backend to OpenGL 2.0 (instead of 3.1) not effect for me.
2. QSG_DISTANCEFIELD_ANTIALIASING DEFAULT=subpixel-lowq not effect too.

for:
    echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf
It works.
ths

**Comment by smoti17** [comment]
>  however, as per #575, this worked just fine:
> 
> echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf

Thank @ShaheedHaque you for this tip, it also solves a similar problem with _kscreenlocker_greet_ which has been annoying me for some years. Before this fix, my "idle" Rasp Pi 4 was burning 2.3W just running _sddm-greeter_ :-(, this is a significant issue on ARM systems where the GPU support is simply not (perhaps yet..) there.

**Comment by jessey-git** [comment]
Just chiming in that I also had to use the workaround suggested above.  In my case I was using a linux vm in the cloud and using remote desktop for login.  The particular vm type I'm using is cheap and gets throttled further according to CPU usage.  Needless to say I was surprised after 2 days of running when I had run out of credits and was subsequently throttled hard :)  Quickly spotted sddm "idling" at a full core of my 2 cpu vm... eventually landed here.

**Comment by AGenchev** [comment]
Thanks for
`echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf`
fixed high CPU usage on XRDP (remote) session to KDE, GPU-less server w dual Xeon silver.

**Comment by pemensik** [comment]
Hi! I have installed lxqt desktop with sddm to Rasberry Pi 4 on Fedora 33, aarch64 builds. sddm eats about 40% of CPU when I do not even have monitor attached. Is there any good default, which should work also with systemd environment file?

```
sddm-0.19.0-6.fc33.aarch64
qt5-qtbase-5.15.2-15.fc33.aarch64
```

**Comment by wtdcode** [comment]
> Using Ubuntu Disco, I found that `QSG_DISTANCEFIELD_ANTIALIASING DEFAULT=subpixel-lowq` had no effect, however, as per #575, this worked just fine:
> 
> ```
> echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf
> ```

This works for me and solves the problem that annoys me for years.

**Comment by pemensik** [comment]
Because high cpu usage happens only when password field has keyboard focus, is there any configuration possible to disable default focus on the input field and require tab or mouseclick to select that? I used sddm on my raspberry, which is usually without display turned on. CPU wasting kind of defeats reason to install lighter desktop environment. I were able to quickly reproduce higher CPU usage on libvirt VM with latest Fedora 35 cd image. Just stopped gdm, then installed and started sddm.

When password has focus, it takes about 10% of CPU. When I press tab, it eats about 0.8%. This is something what I would like by default. I doubt blinking cursor is responsible, that change is too big. Some kind of idle mode would be nice.

Can we change default pam service of sddm-greeter to always include conffile leading to QT_QUICK_BACKEND DEFAULT=software ? I guess most of users wants fast and not CPU eating login, when they choose sddm. It seems better default value. The change does not seem to be visible otherwise. I can confirm it helps on default libvirt VM.

Differences can be easily measure in sddm-greeter --testmode
```
QT_QUICK_BACKEND=default time timeout 10 sddm-greeter --test-mode
1.79user 0.15system 0:10.05elapsed 19%CPU (0avgtext+0avgdata 186460maxresident)k
648inputs+0outputs (1546major+26261minor)pagefaults 0swaps

QT_QUICK_BACKEND=software time timeout 10 sddm-greeter --test-mode
0.38user 0.09system 0:10.01elapsed 4%CPU (0avgtext+0avgdata 124212maxresident)k
0inputs+0outputs (2281major+10809minor)pagefaults 0swaps
```

I think such difference is pretty dramatic. It deserves easier change, if not change of defaults. It should have been lesser with GL acceleration, or not?

**Comment by logecolib** [comment]
This solved it for me on KDE neon inside Hyper-V:

# Add to: /etc/security/pam_env.conf
# Avoid high cpu usage with sddm-greeter
# https://github.com/sddm/sddm/issues/323
QT_QUICK_BACKEND DEFAULT=software

**Comment by pemensik** [comment]
That is nice workaround. But sddm has its own config file. Why cannot this be configured from correct application configuration?
I would like it usable right after package installation. ``/etc/ssdm.conf.d/`` would allow special package setting it for use on VMs without acceleration. But pushing some env parameter to pam is not a good fix, not on proper place.

**Comment by hlovdal** [comment]
I have an older Centos server with a TYAN S7012 motherboard and some "ASPEED Graphics Family (rev 10)" vga controller that had sddm using around 25% cpu constantly. Setting `QT_QUICK_BACKEND DEFAULT=software` as described before fixed the issue.

**Comment by rulatir** [comment]
Any progress on this since February? Forcing some "BACKEND" to "software" is not an acceptable workaround - it amounts to giving up on everything that the likely more performant non-software option might offer.

**Comment by rulatir** [comment]
Any progress on this since February? The workaround suggested above results in what is probably a whole system feature degradation; at least plasma-systemmonitor opens with an alert bar saying that it fell back to software rendering because hardware accelaration is not available.

**Comment by Vogtinator** [comment]
If it's with the breeze theme, that issue should've been fixed ages ago (years at this point?)

**Comment by rulatir** [comment]
> If it's with the breeze theme, that issue should've been fixed ages ago (years at this point?)

I have the breeze theme set for SDDM and I am experiencing this in sddm 0.20.0. Applying the workaround **does** cause greeter's CPU usage to become sane, so this is either still the same issue or a very similar one.

EDIT: After removing the workaround, I switched to another SDDM theme, then dropped out and back into graphical.target, and the high CPU usage was gone. Then I switched to breeze again, and CPU usage is still normal (in fact the sddm-greeter process isn't even running after login).

EDIT 2: The `sddm-greeter` stopped running because it coredumped a while after I logged in again when I got back into graphical.target. I only noticed that later in system logs. However in those instances when it `sddm-greeter` doesn't crash, it does keep grinding.

**Comment by dannylin108** [comment]
My observations: enabling workaround with `QT_QUICK_BACKEND DEFAULT=software`  is not a solution anymore, 'cause it breaks system monitor and a whole bunch of widgets. 

So I have to kill that crazy sddm-greeter manually every time after unlocking the screen, quite annoying actually...  🤯

**Comment by Vogtinator** [comment]
> My observations: enabling workaround with `QT_QUICK_BACKEND DEFAULT=software` is not a solution anymore, 'cause it breaks system monitor and a whole bunch of widgets.
> 
> So I have to kill that crazy sddm-greeter manually every time after unlocking the screen, quite annoying actually... 🤯

Using pam_env for that was never a good idea and will only lead to further issues, like you discovered.

Just use

```
[General]
GreeterEnvironment=QT_QUICK_BACKEND=software
```

instead to only affect the greeter.

**Comment by rulatir** [comment]
> Just use
> 
> ```
> [General]
> GreeterEnvironment=QT_QUICK_BACKEND=software
> ```

Use it where?

**Comment by rulatir** [comment]
> Just use
> 
> ```
> [General]
> GreeterEnvironment=QT_QUICK_BACKEND=software
> ```

**IN
WHICH
FILE**

EDIT: apparently in any .conf file in /etc/sddm.conf.d (that's where I found the workaround already applied), but it doesn't work anyway. As of today, not even locking the screen and tabbing out of the password input helps. This bug is steadily becoming worse, i.e. harder to work around. Looks like it's the workarounds that get "fixed" instead of the bug?

**Comment by rulatir** [comment]
Bug still present as of SDDM 0.21.

**Comment by rulatir** [comment]
Meta question: how come a piece of software the only job of which is to show a greeter and set up a few things so that a DE can run has 500+ open bugs? It's one bug per about how many LOC?

**Comment by Vogtinator** [comment]
> Meta question: how come a piece of software the only job of which is to show a greeter and set up a few things so that a DE can run has 500+ open bugs? It's one bug per about how many LOC?

Meta answer: Many bugs are actually features that need more LoC to implement. Also count LoC of underlying libraries.

**Comment by rulatir** [comment]
Thanks for the meta answer. Meta solution: I switched to lightdm + web-greeter + litarvan theme soon after asking the meta question.

**Comment by sleepy-manul** [comment]
Used the workaround described above:
Create: /etc/sddm.conf.d/sddm-fix-cpu-usage.conf 
Content:

    [General]
    GreeterEnvironment=QT_QUICK_BACKEND=software

Then reboot.

It solved the problem for me (ARM64, RK3588 CPU, openSUSE Tumbleweed), whereas before, sddm used two of eight CPU cores 100% of the time.

**Comment by Joehein** [comment]
Didn't change anything for me. sddm still takes 44% CPU (AMD Threadripper CPU, Nvidia GPU) same as kscreenlocker (55% CPU (2xAMD EPYC, NVIDIA RTX 4080Ti)

**Comment by jmakov** [comment]
@sleepy-manul did you create the directory `/etc/sddm.conf.d` because it's not present on Debian 12

**Comment by sleepy-manul** [comment]
> @sleepy-manul did you create the directory `/etc/sddm.conf.d` because it's not present on Debian 12

I am using openSUSE Tumbleweed (a rolling update distribution). In their packaging, /etc/sddm.conf.d always exists.

**Comment by shelterx** [comment]
> Just use
> 
> ```
> [General]
> GreeterEnvironment=QT_QUICK_BACKEND=software
> ```

Thanks, I had high CPU usage in a KVM and the above fixed it.

**Comment by rulatir** [comment]
```
[General]
GreeterEnvironment=QT_QUICK_BACKEND=software
```
I have this in a file in my sddm.conf.d and it has NO EFFECT. `sddm-greeter` will still fall into a grind sporadically.

I believe that this whole `QT_QUICK_BACKEND=software` thing is a complete red herring. It has no effect on the bug whatsoever. But since the symptom is very sporadic and random, people will often just GET LUCKY after applying the "fix", so they will praise whoever gave them that advice, perpetuating the `QT_QUICK_BACKEND` MYTH.

**Comment by shelterx** [comment]
> I believe that this whole `QT_QUICK_BACKEND=software` thing is a complete red herring. It has no effect on the bug whatsoever.

It does help for some use cases, but there might be more dragons lurking...

**Comment by rulatir** [comment]
> It does help for some use cases, but there might be more dragons lurking...

What is the conclusive, benchmark-backed, test-a-1000-times-with-a-script evidence that even one of those "some use cases" isn't a coincidence where the user applies the "fix" and subsequently gets a lucky streak with the issue randomly not manifesting for a while?

**Comment by robvdl** [comment]
I had the same thing with a Rockchip RK3588 ARM PC, constant 25% CPU usage on all cores until I put

`echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf`

in and it dropped right down to 0% on all cores

I was using a HDMI EDID dummy plug, because without it it was even worse 100% CPU on one core.

With the HDMI EDID dummy plug, 25% on all cores, and with QT_QUICK_BACKEND_DEFAULT=software it dropped right down to 0% CPU usage.

I was using the breeze greeter and Armbian Debian 12.

**Comment by rulatir** [comment]
Also, when will this bug be FIXED?

**Comment by rulatir** [comment]
> I had the same thing with a Rockchip RK3588 ARM PC, constant 25% CPU usage on all cores until I put
> 
> `echo 'QT_QUICK_BACKEND DEFAULT=software' >> /etc/security/pam_env.conf`

Does your desktop look different after applying the fix, or exactly the same?
