### ISSUE TITLE
Logout from wayland freeze the system

### ISSUE THREAD

**Issue by gruel** [sddm/sddm#897]
When logging out of a plasma wayland session the system is completely frozen. There are no other solution than a hard reboot.

It seems to have a lot of thing in common with this bug report.
https://bugs.kde.org/show_bug.cgi?id=370913

I am using archlinux with SDDM version 0.15 and plasma 5.10.5

**Comment by raneon** [comment]
I have the same issue. There is another bug report https://bugs.kde.org/show_bug.cgi?id=372789, but I didn't know that this is probably SDDM itself like in the bug report mentioned by you. I hope as well that it will be addressed soon.

**Comment by raneon** [comment]
I still have this issue with SDDM 0.16 and Plasma 5.11 beta. I tested again with a fresh config file, the default and the breeze theme, but I still get the black screen if I logout of Plasma-Wayland and if I have opened Kate. If Kate is not open, usually I can exit without this crash, maybe that is a hint.

**Comment by simgunz** [comment]
I have the same problem. On Plasma 5.10, for me, it freezes also if I don't open kate.

**Comment by raneon** [comment]
I posted at https://bugs.kde.org/show_bug.cgi?id=372789 the following, hope somebody will be able to tell, whether it is an SDDM issue or not.
journalctl -f shows me the following log (connected via SSH) when I logout from Plasma-Wayland. I use SDDM 0.16, Plasma 5.11, Qt 5.10 beta on Arch Linux.

Okt 12 22:50:03 pc plasmashell[6246]: Unexpected wl_surface.enter received for output with id: 11 screen name: "Screen19" screen model: "eDP-1-unknown"
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: Shutdown called with confirm  -1  type  0  and mode  -1
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: After modifications confirm is  -1  type is  0  and mode  3
Okt 12 22:50:08 pc org_kde_powerdevil[6309]: powerdevil: Scheduling inhibition from ":1.15" "ksmserver" with cookie 1 and reason "Shutting down system"
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: saveSession is  false
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: Saving legacy session apps
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: Done saving  0  legacy session apps
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: clients should be empty,  false
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: completeShutdownOrCheckpoint called
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: completeShutdownOrCheckpoint called
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: state is  7
Okt 12 22:50:08 pc ksmserver[6241]: Error loading text-to-speech plug-in "flite"
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: Starting killing clients
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: startKilling: client  "pulseaudio" ( 10166191167118000150783658300000062410000 )
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: startKilling: client  "/usr/bin/xembedsniproxy" ( 10166191167118000150783658300000062410001 )
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver:  We killed all clients. We have now clients.count()= 2
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: KSMServer::completeKilling clients.count()= 2
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: KSMServer::completeKilling clients.count()= 1
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: KSMServer::completeKilling clients.count()= 0
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: Starting killing WM
Okt 12 22:50:08 pc ksmserver[6241]: ksmserver: KSMServer::completeKillingWM clients.count()= 0
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QThread: Destroyed while thread is still running
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc polkitd[727]: Unregistered Authentication Agent for unix-session:c5 (system bus name :1.205, object path /org/kde/PolicyKit1/AuthenticationAgent, locale de_DE.UTF-8) (disconnected from bus)
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: bluedevil: Destroyed
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc kdeinit5[6214]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc systemd[1]: Started Process Core Dump (PID 7935/UID 0).
Okt 12 22:50:08 pc kactivitymanagerd[6195]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc kwalletd5[6138]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc kactivitymanagerd[6195]: QThread: Destroyed while thread is still running
Okt 12 22:50:08 pc kuiserver5[6361]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_control[6350]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc sddm[596]: kwalletd5: Checking for pam module
Okt 12 22:50:08 pc sddm[596]: kwalletd5: Got pam-login param
Okt 12 22:50:08 pc sddm[596]: kwalletd5: Waiting for hash on 15-
Okt 12 22:50:08 pc sddm[596]: kwalletd5: waitingForEnvironment on: 18
Okt 12 22:50:08 pc sddm[596]: kwalletd5: client connected
Okt 12 22:50:08 pc sddm[596]: kwalletd5: client disconnected
Okt 12 22:50:08 pc akonadi_akonotes_resource[6439]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_sendlater_agent[6454]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_mailfilter_agent[6448]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_archivemail_agent[6440]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_maildispatcher_agent[6447]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_davgroupware_resource[6442]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_followupreminder_agent[6443]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_maildir_resource[6446]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_migration_agent[6449]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_contacts_resource[6441]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_newmailnotifier_agent[6451]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc akonadi_imap_resource[6444]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc kiod5[6806]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc kiod5[6806]: QDBusAbstractAdaptor: Cannot relay signal KDEDModule::moduleDeleted(KDEDModule*): Pointers are not supported: KDEDModule*
Okt 12 22:50:08 pc akonadi_indexing_agent[6445]: The Wayland connection broke. Did the Wayland compositor die?
Okt 12 22:50:08 pc systemd[1]: Started Process Core Dump (PID 7939/UID 0).
Okt 12 22:50:08 pc akonadiserver[6368]: org.kde.pim.akonadiserver: Control process died, committing suicide!
Okt 12 22:50:08 pc akonadi_indexing_agent[6445]: org.kde.pim.akonadicore: "QLocalSocket: Die Verbindung wurde von der Gegenseite geschlossen" "/tmp/akonadi-rainer.81PJW1/akonadiserver-cmd.socket"
Okt 12 22:50:08 pc kernel: kwin_wayland[6168]: segfault at 7fe7c6321680 ip 00007fe7cc30b1f0 sp 00007ffce0917620 error 4 in libEGL_mesa.so.0.0.0[7fe7cc2f5000+36000]
Okt 12 22:50:08 pc akonadi_newmailnotifier_agent[6451]: org.kde.pim.akonadicore: "QLocalSocket: Die Verbindung wurde von der Gegenseite geschlossen" "/tmp/akonadi-rainer.81PJW1/akonadiserver-cmd.socket"
Okt 12 22:50:08 pc akonadi_davgroupware_resource[6442]: "QLocalSocket: Die Verbindung wurde von der Gegenseite geschlossen" "/tmp/akonadi-rainer.81PJW1/akonadiserver-cmd.socket"
Okt 12 22:50:08 pc akonadi_imap_resource[6444]: org.kde.pim.akonadicore: "QLocalSocket: Die Verbindung wurde von der Gegenseite geschlossen" "/tmp/akonadi-rainer.81PJW1/akonadiserver-cmd.socket"
Okt 12 22:50:08 pc akonadi_newmailnotifier_agent[6451]: org.kde.pim.akonadicore: "QLocalSocket: Die Verbindung wurde von der Gegenseite geschlossen" "/tmp/akonadi-rainer.81PJW1/akonadiserver-cmd.socket"
Okt 12 22:50:08 pc akonadiserver[6368]: chainup()
Okt 12 22:50:08 pc systemd[1]: Started Process Core Dump (PID 7945/UID 0).
Okt 12 22:50:08 pc systemd-coredump[7936]: Process 6214 (kded5) of user 1000 dumped core.
                                                        
                                                        Stack trace of thread 6214:
                                                        #0  0x00007f3163aa98a0 raise (libc.so.6)
                                                        #1  0x00007f31656fdfca _ZN6KCrash19defaultCrashHandlerEi (libKF5Crash.so.5)
                                                        #2  0x00007f3163aa9920 __restore_rt (libc.so.6)
                                                        #3  0x00007f3163aa98a0 raise (libc.so.6)
                                                        #4  0x00007f3163aaaf09 abort (libc.so.6)
                                                        #5  0x00007f3163aec517 __libc_message (libc.so.6)
                                                        #6  0x00007f3163af2c84 malloc_printerr (libc.so.6)
                                                        #7  0x00007f3163af3162 malloc_consolidate (libc.so.6)
                                                        #8  0x00007f3163af5f52 _int_malloc (libc.so.6)
                                                        #9  0x00007f3163af7af4 malloc (libc.so.6)
                                                        #10 0x00007f3163ae1c7d _IO_file_doallocate (libc.so.6)
                                                        #11 0x00007f3163af06d9 _IO_doallocbuf (libc.so.6)
                                                        #12 0x00007f3163aef958 _IO_file_overflow@@GLIBC_2.2.5 (libc.so.6)
                                                        #13 0x00007f3163aee9c7 _IO_file_xsputn@@GLIBC_2.2.5 (libc.so.6)
                                                        #14 0x00007f3163ac1fdc vfprintf (libc.so.6)
                                                        #15 0x00007f3163acaaa6 _IO_printf (libc.so.6)
                                                        #16 0x00007f31656fcd72 n/a (libKF5Crash.so.5)
                                                        #17 0x00007f31656fd82b n/a (libKF5Crash.so.5)
                                                        #18 0x00007f31656fdf43 _ZN6KCrash19defaultCrashHandlerEi (libKF5Crash.so.5)
                                                        #19 0x00007f3163aa9920 __restore_rt (libc.so.6)
                                                        #20 0x00007f3153f2a7f9 n/a (libwayland-client.so.0)
                                                        #21 0x00007f3153f267e7 wl_proxy_destroy (libwayland-client.so.0)
                                                        #22 0x00007f315270f529 _ZN8KWayland6Client12PlasmaWindow7releaseEv (libKF5WaylandClient.so.5)
                                                        #23 0x00007f315270f54b _ZN8KWayland6Client12PlasmaWindowD1Ev (libKF5WaylandClient.so.5)
                                                        #24 0x00007f315270f64a _ZN8KWayland6Client12PlasmaWindowD0Ev (libKF5WaylandClient.so.5)
                                                        #25 0x00007f31640f5bed _ZN14QObjectPrivate14deleteChildrenEv (libQt5Core.so.5)
                                                        #26 0x00007f31640ff81c _ZN7QObjectD2Ev (libQt5Core.so.5)
                                                        #27 0x00007f315270ec7a _ZN8KWayland6Client22PlasmaWindowManagementD0Ev (libKF5WaylandClient.so.5)
                                                        #28 0x00007f31640f5bed _ZN14QObjectPrivate14deleteChildrenEv (libQt5Core.so.5)
                                                        #29 0x00007f31640ff81c _ZN7QObjectD2Ev (libQt5Core.so.5)
                                                        #30 0x00007f3114829fc4 n/a (KF5WindowSystemKWaylandPlugin.so)
                                                        #31 0x00007f3163aac488 __run_exit_handlers (libc.so.6)
                                                        #32 0x00007f3163aac4da exit (libc.so.6)
                                                        #33 0x0000558c72de0051 n/a (kdeinit5)
                                                        #34 0x0000558c72ddcb69 n/a (kdeinit5)
                                                        #35 0x00007f3163a95f6a __libc_start_main (libc.so.6)
                                                        #36 0x0000558c72ddd1ba _start (kdeinit5)
                                                        
                                                        Stack trace of thread 6235:
                                                        #0  0x00007f3163b60d4b __poll (libc.so.6)
                                                        #1  0x00007f315ff10ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f315ff10fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f315ff11002 n/a (libglib-2.0.so.0)
                                                        #4  0x00007f315ff051eb n/a (libglib-2.0.so.0)
                                                        #5  0x00007f3161fd008a start_thread (libpthread.so.0)
                                                        #6  0x00007f3163b6b24f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6236:
                                                        #0  0x00007f3163b60d4b __poll (libc.so.6)
                                                        #1  0x00007f315ff10ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f315ff11f42 g_main_loop_run (libglib-2.0.so.0)
                                                        #3  0x00007f314c2b6e28 n/a (libgio-2.0.so.0)
                                                        #4  0x00007f315ff051eb n/a (libglib-2.0.so.0)
                                                        #5  0x00007f3161fd008a start_thread (libpthread.so.0)
                                                        #6  0x00007f3163b6b24f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6285:
                                                        #0  0x00007f3163b391e0 __nanosleep (libc.so.6)
                                                        #1  0x00007f316412369f n/a (libQt5Core.so.5)
                                                        #2  0x00007f31656fdc2f _ZN6KCrash19defaultCrashHandlerEi (libKF5Crash.so.5)
                                                        #3  0x00007f3163aa9920 __restore_rt (libc.so.6)
                                                        #4  0x00007f3163aa98a0 raise (libc.so.6)
                                                        #5  0x00007f3163aaaf09 abort (libc.so.6)
                                                        #6  0x00007f3163ec5388 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                                                        #7  0x00007f3163ed3a7e _ZN7QThreadD2Ev (libQt5Core.so.5)
                                                        #8  0x00007f3163ed3ada _ZN7QThreadD0Ev (libQt5Core.so.5)
                                                        #9  0x00007f31640f5bed _ZN14QObjectPrivate14deleteChildrenEv (libQt5Core.so.5)
                                                        #10 0x00007f31640ff81c _ZN7QObjectD2Ev (libQt5Core.so.5)
                                                        #11 0x00007f3145ccae3a n/a (kded_printmanager.so)
                                                        #12 0x00007f31640f8b11 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                                                        #13 0x00007f316253bc8c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                        #14 0x00007f3162543666 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                        #15 0x00007f31640c7880 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                        #16 0x00007f31640ca4e6 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
                                                        #17 0x00007f3164124744 n/a (libQt5Core.so.5)
                                                        #18 0x00007f315ff0f270 g_main_context_dispatch (libglib-2.0.so.0)
                                                        #19 0x00007f315ff10f69 n/a (libglib-2.0.so.0)
                                                        #20 0x00007f315ff10fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #21 0x00007f3164123d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #22 0x00007f31640c5ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #23 0x00007f3163ed4bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #24 0x00007f3163ed9d9d n/a (libQt5Core.so.5)
                                                        #25 0x00007f3161fd008a start_thread (libpthread.so.0)
                                                        #26 0x00007f3163b6b24f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6327:
                                                        #0  0x00007f3163b60d4b __poll (libc.so.6)
                                                        #1  0x00007f315ff10ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f315ff10fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f3164123d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f31640c5ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f3163ed4bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x00007f3163ed9d9d n/a (libQt5Core.so.5)
                                                        #7  0x00007f3161fd008a start_thread (libpthread.so.0)
                                                        #8  0x00007f3163b6b24f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6326:
                                                        #0  0x00007f3163b60d4b __poll (libc.so.6)
                                                        #1  0x00007f315ff10ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f315ff10fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f3164123d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f31640c5ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f3163ed4bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x00007f3163ed9d9d n/a (libQt5Core.so.5)
                                                        #7  0x00007f3161fd008a start_thread (libpthread.so.0)
                                                        #8  0x00007f3163b6b24f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6217:
                                                        #0  0x00007f3163b60d4b __poll (libc.so.6)
                                                        #1  0x00007f315ff10ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f315ff10fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f3164123d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f31640c5ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f3163ed4bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x00007f315b501416 n/a (libQt5DBus.so.5)
                                                        #7  0x00007f3163ed9d9d n/a (libQt5Core.so.5)
                                                        #8  0x00007f3161fd008a start_thread (libpthread.so.0)
                                                        #9  0x00007f3163b6b24f __clone (libc.so.6)
Okt 12 22:50:08 pc systemd-coredump[7940]: Process 6195 (kactivitymanage) of user 1000 dumped core.
                                                        
                                                        Stack trace of thread 6195:
                                                        #0  0x00007f9ed50c68a0 raise (libc.so.6)
                                                        #1  0x00007f9ed50c7f09 abort (libc.so.6)
                                                        #2  0x00007f9ed5869388 _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
                                                        #3  0x00007f9ed5877a7e _ZN7QThreadD2Ev (libQt5Core.so.5)
                                                        #4  0x00007f9eb3bdea4c n/a (kactivitymanagerd_plugin_sqlite.so)
                                                        #5  0x00007f9ed50c9488 __run_exit_handlers (libc.so.6)
                                                        #6  0x00007f9ed50c94da exit (libc.so.6)
                                                        #7  0x00007f9ecd833def _ZN15QtWaylandClient15QWaylandDisplay13exitWithErrorEv (libQt5WaylandClient.so.5)
                                                        #8  0x00007f9ecd833e4a _ZN15QtWaylandClient15QWaylandDisplay13flushRequestsEv (libQt5WaylandClient.so.5)
                                                        #9  0x00007f9ed5a9c0a6 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                                        #10 0x00007f9ed5aa89e9 _ZN15QSocketNotifier9activatedEiNS_14QPrivateSignalE (libQt5Core.so.5)
                                                        #11 0x00007f9ed5aa8dc4 _ZN15QSocketNotifier5eventEP6QEvent (libQt5Core.so.5)
                                                        #12 0x00007f9ed67afc8c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                        #13 0x00007f9ed67b7666 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                        #14 0x00007f9ed5a6b880 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                        #15 0x00007f9ed5ac89ce n/a (libQt5Core.so.5)
                                                        #16 0x00007f9ed1f92270 g_main_context_dispatch (libglib-2.0.so.0)
                                                        #17 0x00007f9ed1f93f69 n/a (libglib-2.0.so.0)
                                                        #18 0x00007f9ed1f93fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #19 0x00007f9ed5ac7d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #20 0x00007f9ecd86bb42 n/a (libQt5WaylandClient.so.5)
                                                        #21 0x00007f9ed5a69ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #22 0x00007f9ed5a731b8 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                                        #23 0x000056268f686f6f n/a (kactivitymanagerd)
                                                        #24 0x00007f9ed50b2f6a __libc_start_main (libc.so.6)
                                                        #25 0x000056268f6871ca _start (kactivitymanagerd)
                                                        
                                                        Stack trace of thread 6208:
                                                        #0  0x00007f9ed517dd4b __poll (libc.so.6)
                                                        #1  0x00007f9ed1f93ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f9ed1f93fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f9ed5ac7d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f9ed5a69ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f9ed5878bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x000056268f68945b n/a (kactivitymanagerd)
                                                        #7  0x00007f9ed587dd9d n/a (libQt5Core.so.5)
                                                        #8  0x00007f9ed3d4c08a start_thread (libpthread.so.0)
                                                        #9  0x00007f9ed518824f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6209:
                                                        #0  0x00007f9ed517dd4b __poll (libc.so.6)
                                                        #1  0x00007f9ed1f93ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f9ed1f93fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f9ed5ac7d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f9ed5a69ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f9ed5878bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x000056268f68948b n/a (kactivitymanagerd)
                                                        #7  0x00007f9ed587dd9d n/a (libQt5Core.so.5)
                                                        #8  0x00007f9ed3d4c08a start_thread (libpthread.so.0)
                                                        #9  0x00007f9ed518824f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6207:
                                                        #0  0x00007f9ed517dd4b __poll (libc.so.6)
                                                        #1  0x00007f9ed1f93ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f9ed1f93fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f9ed5ac7d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f9ed5a69ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f9ed5878bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x00007f9ed63e8416 n/a (libQt5DBus.so.5)
                                                        #7  0x00007f9ed587dd9d n/a (libQt5Core.so.5)
                                                        #8  0x00007f9ed3d4c08a start_thread (libpthread.so.0)
                                                        #9  0x00007f9ed518824f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 7341:
                                                        #0  0x00007f9ed51561e0 __nanosleep (libc.so.6)
                                                        #1  0x00007f9ed5ac769f n/a (libQt5Core.so.5)
                                                        #2  0x00007f9eb3bde31c n/a (kactivitymanagerd_plugin_sqlite.so)
                                                        #3  0x00007f9ed587dd9d n/a (libQt5Core.so.5)
                                                        #4  0x00007f9ed3d4c08a start_thread (libpthread.so.0)
                                                        #5  0x00007f9ed518824f __clone (libc.so.6)
                                                        
                                                        Stack trace of thread 6210:
                                                        #0  0x00007f9ed517dd4b __poll (libc.so.6)
                                                        #1  0x00007f9ed1f93ed3 n/a (libglib-2.0.so.0)
                                                        #2  0x00007f9ed1f93fae g_main_context_iteration (libglib-2.0.so.0)
                                                        #3  0x00007f9ed5ac7d31 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #4  0x00007f9ed5a69ecb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                        #5  0x00007f9ed5878bfe _ZN7QThread4execEv (libQt5Core.so.5)
                                                        #6  0x000056268f6894bb n/a (kactivitymanagerd)
                                                        #7  0x00007f9ed587dd9d n/a (libQt5Core.so.5)
                                                        #8  0x00007f9ed3d4c08a start_thread (libpthread.so.0)
                                                        #9  0x00007f9ed518824f __clone (libc.so.6)
Okt 12 22:50:59 pc systemd-coredump[7946]: Core file was truncated to 2147483648 bytes.
Okt 12 22:51:26 pc systemd-coredump[7946]: Process 6168 (kwin_wayland) of user 1000 dumped core.
                                                        
                                                        Stack trace of thread 6168:
                                                        #0  0x00007fe7cc30b1f0 n/a (n/a)
Okt 12 22:51:27 pc sddm-helper[6136]: [PAM] Closing session
Okt 12 22:51:27 pc sddm-helper[6136]: pam_unix(sddm:session): session closed for user rainer
Okt 12 22:51:27 pc sddm-helper[6136]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_close_session
Okt 12 22:51:27 pc sddm-helper[6136]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
Okt 12 22:51:27 pc sddm-helper[6136]: [PAM] Ended.
Okt 12 22:51:27 pc sddm[596]: Auth: sddm-helper exited successfully
Okt 12 22:51:27 pc sddm[596]: Greeter stopping...
Okt 12 22:51:27 pc sddm[596]: Socket server stopping...
Okt 12 22:51:27 pc sddm[596]: Socket server stopped.
Okt 12 22:51:27 pc sddm[596]: Display server stopping...
Okt 12 22:51:27 pc sddm-greeter[2969]: The X11 connection broke: I/O error (code 1)
Okt 12 22:51:27 pc sddm-helper[2960]: [PAM] Closing session
Okt 12 22:51:27 pc sddm-helper[2960]: pam_unix(sddm-greeter:session): session closed for user sddm
Okt 12 22:51:27 pc sddm-helper[2960]: [PAM] Ended.
Okt 12 22:51:27 pc systemd-logind[571]: Removed session c5.
Okt 12 22:51:27 pc systemd-logind[571]: Removed session c3.
Okt 12 22:51:27 pc systemd[2962]: Stopped target Default.
Okt 12 22:51:27 pc systemd[2962]: Stopping D-Bus User Message Bus...
Okt 12 22:51:27 pc systemd[2962]: Stopped D-Bus User Message Bus.
Okt 12 22:51:27 pc systemd[2962]: Stopped target Basic System.
Okt 12 22:51:27 pc systemd[2962]: Stopped target Timers.
Okt 12 22:51:27 pc systemd[2962]: Stopped target Paths.
Okt 12 22:51:27 pc systemd[2962]: Stopped target Sockets.
Okt 12 22:51:27 pc systemd[2962]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Okt 12 22:51:27 pc systemd[2962]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Okt 12 22:51:27 pc systemd[2962]: Closed Sound System.
Okt 12 22:51:27 pc systemd[2962]: Closed GnuPG cryptographic agent and passphrase cache.
Okt 12 22:51:27 pc systemd[2962]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Okt 12 22:51:27 pc systemd[2962]: Closed GnuPG network certificate management daemon.
Okt 12 22:51:27 pc systemd[2962]: Closed D-Bus User Message Bus Socket.
Okt 12 22:51:27 pc systemd[2962]: Reached target Shutdown.
Okt 12 22:51:27 pc systemd[2962]: Starting Exit the Session...
Okt 12 22:51:27 pc systemd[1]: Stopping User Manager for UID 618...
Okt 12 22:51:27 pc systemd[2962]: Received SIGRTMIN+24 from PID 7964 (kill).
Okt 12 22:51:27 pc systemd[2963]: pam_unix(systemd-user:session): session closed for user sddm
Okt 12 22:51:27 pc systemd[1]: Stopped User Manager for UID 618.
Okt 12 22:51:27 pc systemd[1]: Removed slice User Slice of sddm.
Okt 12 22:51:28 pc akonadiserver[6368]: D-Bus session bus went down - quitting
Okt 12 22:51:32 pc sddm[596]: Removing display ":0" ...
Okt 12 22:51:32 pc sddm[596]: Adding new display on vt 1 ...
Okt 12 22:51:32 pc sddm[596]: Loading theme configuration from ""
Okt 12 22:51:32 pc sddm[596]: Display server starting...
Okt 12 22:51:32 pc sddm[596]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{a91f244d-c28e-4e69-8d3f-7ef84146a5a0} -background none -noreset -displayfd 24 -seat seat0 vt1
Okt 12 22:51:32 pc systemd-logind[571]: Received VT_PROCESS signal without a registered session on that VT.

**Comment by gruel** [comment]
Correction, logout from KDE wayland (plasma+kwayland) is the problem. Logout from a gnome session does work like a charm.

**Comment by raneon** [comment]
Do you mean gnome-session on Wayland or X11? And how is this related to Plasma-Wayland and the exit to SDDM? Because a normal logout from Plasma on X11 works as well like a charm.

**Comment by gruel** [comment]
Obviously I was meaning logout from a Wayland gnome session is working without any problem with SDDM (X11 also) when plasma logout work only for X11. The wayland plasma logout is freezing and providing  a left upper side of garbage and a black screen (before it was a full black frozen screen).

**Comment by raneon** [comment]
At least for me this seems to be fixed with SDDM 0.17. Can anyone else confirm this?

**Comment by raneon** [comment]
The system still freezes sometimes during logout from Plasma-Wayland. I assume it is related to XWayland.

**Comment by Pointedstick** [comment]
I (and at least one other person) can confirm that this issue is fixed with SDDM 0.17 in Plasma 5.13: https://bugs.kde.org/show_bug.cgi?id=372789#c29

Since nothing changed on the SDDM side, I have to assume that this was in fact a KDE issue, not an SDDM issue. Accordingly, I recommend closing the ticket (can't do it myself; no privileges).

**Comment by soreau** [comment]
I set minimum tty to 7 but it still starts wayfire wayland compositor always on tty1. When I exit the compositor, it was leaving no way to change tty but now that I added 'exec' to my script, it doesn't get stuck on tty1. However, sddm is black when I switch back to tty7 manually and I have to restart it to get it back.

**Comment by miguelcaravantes** [comment]
Same problem on logout from kde plasma session

**Comment by Seqularise** [comment]
its been like that for a long time, i personally just restart sddm from tty to make this work

**Comment by meven** [comment]
I don't reproduce in Plasma 5.19.80 (a bunch of crashes in KWin were fixed in 5.19/5.20 like https://bugs.kde.org/show_bug.cgi?id=420077).
I don't think this was a sddm issue.

**Comment by Pointedstick** [comment]
Agreed.

**Comment by bam80** [comment]
> I don't reproduce in Plasma 5.19.80

Shall we close it then?

**Comment by glaubersm** [comment]
Hi
I'm the reporter of the kwin bug linked by meven.
Neon unstable is still getting stuck in a black screen witthout cursor because kwin crash on logout from Wayland session,
but such problem is no longer consistently reproducible. Apparently it occurs randomly.
I'm not sure if this problem with logout from Wayland session has something to do with SDDM because it’s been a long time since it occurred on my Arch Linux running the same version of SDDM (0.18.1).

**Comment by bam80** [comment]
> I don't reproduce in Plasma 5.19.80 (a bunch of crashes in KWin were fixed in 5.19/5.20 like https://bugs.kde.org/show_bug.cgi?id=420077).
> I don't think this was a sddm issue.

The linked issue doesn't related with SDDM indeed - the crash is still reproduced and I'm on GDM, so I've reopened it.

**Comment by bam80** [comment]
Please retest, upstream related issue was fixed recently:
https://bugs.kde.org/show_bug.cgi?id=420077

**Comment by glaubersm** [comment]
I confirm that kwin-wayland crash is fixed on neon unstable based on ubuntu 20.04 and my system no longer gets stuck in a black screen on logout from Wayland session.

**Comment by Pointedstick** [comment]
Cool, closing.
